Importamos pandas en el proyecto

In [5]:
import pandas as pd

Cremaos un diccionario de paises

In [4]:
dataPaises = {
    "pais": ["España", "Francia", "Colombia", "Mexico", "Perú", "Suiza"],
    "capital": ["Madrid", "París", "Bogotá", "CDMX", "Lima", "Praga"],
    "superficie": [1.9, 2.6, 3.9, 4.0, 2.8, 3.5]
}

Creamos un DataFrame con el diccionario.

In [6]:
df = pd.DataFrame(dataPaises)
df

       pais capital  superficie
0    España  Madrid         1.9
1   Francia   París         2.6
2  Colombia  Bogotá         3.9
3    Mexico    CDMX         4.0
4      Perú    Lima         2.8
5     Suiza   Praga         3.5

por ejemplo, podemos dibujar solamente una columna

In [8]:
df[['capital', 'superficie']]

  capital  superficie
0  Madrid         1.9
1   París         2.6
2  Bogotá         3.9
3    CDMX         4.0
4    Lima         2.8
5   Praga         3.5

se pueden seleccionar filas por su posicion del índice.
Primero incluido y el segundo no incluido.

In [9]:
df[2:5]

       pais capital  superficie
2  Colombia  Bogotá         3.9
3    Mexico    CDMX         4.0
4      Perú    Lima         2.8

Por defecto, los indices d elos elementos son numéricos y los pone automaticamente.
podemos crear nuestros propios indices y sustituir el index

In [11]:
df.index = ["ES", "FR", "CO", "MX", "PE", "SZ"]
df = df.reset_index()
df

  index      pais capital  superficie
0    ES    España  Madrid         1.9
1    FR   Francia   París         2.6
2    CO  Colombia  Bogotá         3.9
3    MX    Mexico    CDMX         4.0
4    PE      Perú    Lima         2.8
5    SZ     Suiza   Praga         3.5