In [1]:
import pandas as pd

Leemos el fichero de datos dentro del DataFrame

In [2]:
df = pd.read_csv('data/iris.data')
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

Dibujar un número N de filas.

In [3]:
df.head(2)

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa

Podemos dibujar las últimas con .tail

In [4]:
df.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

No tenemos nombres de cabeceras ilustrativos
Podemos incluir los nombres de las columnas mediante una lista

In [5]:
nombres = ['longitud_sepalo', 'ancho_sepalo', 'longitud_petalo', 'ancho_petalo', 'especie']
df.columns = nombres
df

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,especie
0,4.9,3.0,1.4,0.2,Iris-setosa
1,4.7,3.2,1.3,0.2,Iris-setosa
2,4.6,3.1,1.5,0.2,Iris-setosa
3,5.0,3.6,1.4,0.2,Iris-setosa
4,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...
144,6.7,3.0,5.2,2.3,Iris-virginica
145,6.3,2.5,5.0,1.9,Iris-virginica
146,6.5,3.0,5.2,2.0,Iris-virginica
147,6.2,3.4,5.4,2.3,Iris-virginica
148,5.9,3.0,5.1,1.8,Iris-virginica

Podemos averiguar los datos de nuestro df (filas y columnas)

In [6]:
df.shape

(149, 5)

con describe() nos indica estadísticas d elos datos

In [7]:
df.describe()

       longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo
count       149.000000    149.000000       149.000000    149.000000
mean          5.848322      3.051007         3.774497      1.205369
std           0.828594      0.433499         1.759651      0.761292
min           4.300000      2.000000         1.000000      0.100000
25%           5.100000      2.800000         1.600000      0.300000
50%           5.800000      3.000000         4.400000      1.300000
75%           6.400000      3.300000         5.100000      1.800000
max           7.900000      4.400000         6.900000      2.500000

Podemos ordenar los valores

In [11]:
df.sort_values('longitud_sepalo', ascending=False)

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,especie
130,7.9,3.8,6.4,2.0,Iris-virginica
134,7.7,3.0,6.1,2.3,Iris-virginica
121,7.7,2.8,6.7,2.0,Iris-virginica
116,7.7,3.8,6.7,2.2,Iris-virginica
117,7.7,2.6,6.9,2.3,Iris-virginica
...,...,...,...,...,...
40,4.5,2.3,1.3,0.3,Iris-setosa
7,4.4,2.9,1.4,0.2,Iris-setosa
41,4.4,3.2,1.3,0.2,Iris-setosa
37,4.4,3.0,1.3,0.2,Iris-setosa
12,4.3,3.0,1.1,0.1,Iris-setosa

Podemos realizar filtros sobre los datos (simples)

In [12]:
df[df['longitud_petalo'] > 5]

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,especie
82,6.0,2.7,5.1,1.6,Iris-versicolor
99,6.3,3.3,6.0,2.5,Iris-virginica
100,5.8,2.7,5.1,1.9,Iris-virginica
101,7.1,3.0,5.9,2.1,Iris-virginica
102,6.3,2.9,5.6,1.8,Iris-virginica
103,6.5,3.0,5.8,2.2,Iris-virginica
104,7.6,3.0,6.6,2.1,Iris-virginica
106,7.3,2.9,6.3,1.8,Iris-virginica
107,6.7,2.5,5.8,1.8,Iris-virginica
108,7.2,3.6,6.1,2.5,Iris-virginica
109,6.5,3.2,5.1,2.0,Iris-virginica
110,6.4,2.7,5.3,1.9,Iris-virginica
111,6.8,3.0,5.5,2.1,Iris-virginica
113,5.8,2.8,5.1,2.4,Iris-virginica
114,6.4,3.2,5.3,2.3,Iris-virginica
115,6.5,3.0,5.5,1.8,Iris-virginica
116,7.7,3.8,6.7,2.2,Iris-virginica
117,7.7,2.6,6.9,2.3,Iris-virginica
119,6.9,3.2,5.7,2.3,Iris-virginica
121,7.7,2.8,6.7,2.0,Iris-virginica
123,6.7,3.3,5.7,2.1,Iris-virginica
124,7.2,3.2,6.0,1.8,Iris-virginica
127,6.4,2.8,5.6,2.1,Iris-virginica
128,7.2,3.0,5.8,1.6,Iris-virginica
129,7.4,2.8,6.1,1.9,Iris-virginica
130,7.9,3.8,6.4,2.0,Iris-virginica
131,6.4,2.8,5.6,2.2,Iris-virginica
132,6.3,2.8,5.1,1.5,Iris-virginica
133,6.1,2.6,5.6,1.4,Iris-virginica
134,7.7,3.0,6.1,2.3,Iris-virginica
135,6.3,3.4,5.6,2.4,Iris-virginica
136,6.4,3.1,5.5,1.8,Iris-virginica
138,6.9,3.1,5.4,2.1,Iris-virginica
139,6.7,3.1,5.6,2.4,Iris-virginica
140,6.9,3.1,5.1,2.3,Iris-virginica
141,5.8,2.7,5.1,1.9,Iris-virginica
142,6.8,3.2,5.9,2.3,Iris-virginica
143,6.7,3.3,5.7,2.5,Iris-virginica
144,6.7,3.0,5.2,2.3,Iris-virginica
146,6.5,3.0,5.2,2.0,Iris-virginica
147,6.2,3.4,5.4,2.3,Iris-virginica
148,5.9,3.0,5.1,1.8,Iris-virginica

Para filtros mas complejos se utiliza la siguiente sintaxis:
AND: &
OR: |
Longitud del petalo > 5 y ancho del petalo < 1.5

In [16]:
df[(df['longitud_petalo'] > 5) & (df['ancho_petalo'] < 1.5)]

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,especie
133,6.1,2.6,5.6,1.4,Iris-virginica

Se pueden hacer operaciones matematicas sobre los datos

In [19]:
df['longitud_petalo'] - df['longitud_sepalo']

0     -3.5
1     -3.4
2     -3.1
3     -3.6
4     -3.7
      ...
144   -1.5
145   -1.3
146   -1.3
147   -0.8
148   -0.8
Length: 149, dtype: float64

Podemos visualizar operaciones sobre el grupo del DF
media

In [26]:
media = df['longitud_petalo'].mean()
maximo = df['longitud_petalo'].max()
texto = f"Media: {media}, Máximo: {maximo}"
texto

'Media: 3.774496644295302, Máximo: 6.9'

por supuesto, podemos aplicar lambda a nuestros DataFrames. Se realiza mediante el metodo apply()

In [28]:
df['longitud_petalo'].apply(lambda x: -x)

0     -1.4
1     -1.3
2     -1.5
3     -1.4
4     -1.7
      ...
144   -5.2
145   -5.0
146   -5.2
147   -5.4
148   -5.1
Name: longitud_petalo, Length: 149, dtype: float64

Doble

In [ ]:
df['longitud_petalo'].apply(lambda x: x*2) 
df.insert

0       2.8
1       2.6
2       3.0
3       2.8
4       3.4
       ...
144    10.4
145    10.0
146    10.4
147    10.8
148    10.2
Name: longitud_petalo, Length: 149, dtype: float64

averiguar la informacion de nuestro DataFrame, es decir, saber si dentro existen valores nullos que no vengan en la Serie

In [35]:
df.isna().sum()

longitud_sepalo    0
ancho_sepalo       0
longitud_petalo    0
ancho_petalo       0
especie            0
dtype: int64

Mediante info() tambien podemos averiguar dicha informacion

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   longitud_sepalo  149 non-null    float64
 1   ancho_sepalo     149 non-null    float64
 2   longitud_petalo  149 non-null    float64
 3   ancho_petalo     149 non-null    float64
 4   especie          149 non-null    str
dtypes: float64(4), str(1)
memory usage: 5.9 KB

Vamos a averiguar que podemos hacer su tuvieramos valores nulos dentro d enuestros datos.
Para trabajar con estos valores se usa la libreria numpy

In [37]:
import numpy as np

incluimos valores nulos en un par de filas: np.nan

In [40]:
df.loc[:2, 'longitud_petalo'] = np.nan
df.head()

   longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo      especie
0              4.9           3.0              NaN           0.2  Iris-setosa
1              4.7           3.2              NaN           0.2  Iris-setosa
2              4.6           3.1              NaN           0.2  Iris-setosa
3              5.0           3.6              1.4           0.2  Iris-setosa
4              5.4           3.9              1.7           0.4  Iris-setosa

In [42]:
df.isna().sum()

longitud_sepalo    0
ancho_sepalo       0
longitud_petalo    3
ancho_petalo       0
especie            0
dtype: int64

Los datos nulos son elementos de lo mas normal dentro de un DataFrame, datos qye bi se han rellenado. Para tratar datos nulos, tenemos un par de opciones
dropna() --> Elimina la columna/filas con nulos
Podemos indicar axis=0 para filas
axis = 1 para columnas

In [43]:
df_limpio = df.dropna(axis=1)
df_limpio.head()

   longitud_sepalo  ancho_sepalo  ancho_petalo      especie
0              4.9           3.0           0.2  Iris-setosa
1              4.7           3.2           0.2  Iris-setosa
2              4.6           3.1           0.2  Iris-setosa
3              5.0           3.6           0.2  Iris-setosa
4              5.4           3.9           0.4  Iris-setosa

In [46]:
df_filas = df.dropna(axis=0)
df_filas.head()

   longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo      especie
3              5.0           3.6              1.4           0.2  Iris-setosa
4              5.4           3.9              1.7           0.4  Iris-setosa
5              4.6           3.4              1.4           0.3  Iris-setosa
6              5.0           3.4              1.5           0.2  Iris-setosa
7              4.4           2.9              1.4           0.2  Iris-setosa

In [48]:
df.loc[:4, 'longitud_petalo'] = np.nan
df.head(10)

   longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo      especie
0              4.9           3.0              NaN           0.2  Iris-setosa
1              4.7           3.2              NaN           0.2  Iris-setosa
2              4.6           3.1              NaN           0.2  Iris-setosa
3              5.0           3.6              NaN           0.2  Iris-setosa
4              5.4           3.9              NaN           0.4  Iris-setosa
5              4.6           3.4              1.4           0.3  Iris-setosa
6              5.0           3.4              1.5           0.2  Iris-setosa
7              4.4           2.9              1.4           0.2  Iris-setosa
8              4.9           3.1              1.5           0.1  Iris-setosa
9              5.4           3.7              1.5           0.2  Iris-setosa

La otra posibilidad está en poder operar con los datos dentro del DataFrame.
Un Null es lo mismo aquí que en base d edatos, no se tiene en cuenta.
En lugar d elimpiar el DataFrame de nuelos, podemos modificar valores nulos tambien.
Es decir, quitar el null y poner un valor por defecto.
Para ello se utiliza fillna(valor)

In [53]:
df['longitud_petalo'] = df['longitud_petalo'].fillna(999)
df.head(10)

   longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo      especie
0              4.9           3.0            999.0           0.2  Iris-setosa
1              4.7           3.2            999.0           0.2  Iris-setosa
2              4.6           3.1            999.0           0.2  Iris-setosa
3              5.0           3.6            999.0           0.2  Iris-setosa
4              5.4           3.9            999.0           0.4  Iris-setosa
5              4.6           3.4              1.4           0.3  Iris-setosa
6              5.0           3.4              1.5           0.2  Iris-setosa
7              4.4           2.9              1.4           0.2  Iris-setosa
8              4.9           3.1              1.5           0.1  Iris-setosa
9              5.4           3.7              1.5           0.2  Iris-setosa

Tmbién podemos crear agrupaciones para averiguar caracteristicas respecto a una columna. esto es lo mismo que un group by de SQL

In [59]:
df_grupo = df.groupby('especie')['ancho_petalo'].mean()
df_grupo

especie
Iris-setosa        0.244898
Iris-versicolor    1.326000
Iris-virginica     2.026000
Name: ancho_petalo, dtype: float64

Por supuesto podemos realizar hasta dibujos!!!!!!
Con la libreria matplotlib

In [60]:
import matplotlib.pyplot as plt

In [ ]:
df_grupo.plot(kind='area', y='ancho_petalo')